title: Rebecca Pattichis
#description: Cayman is a clean, responsive theme for GitHub Pages.
#show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
buttons:
  resume_url: https://drive.google.com/file/d/1CsjW28mS2S3z1u2An7jOVj4l4ZlRlvuS/view?usp=sharing
  linkedin_url: https://linkedin.com/in/rebecca-pattichis
  twitter_url: https://twitter.com/rpattichi
  github_url: https://github.com/rpattichis
